sonar.projectKey=shopping-cart-localization
sonar.projectName=Shopping Cart Localization
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.host.url=http://localhost:9000
